### ISSUE TITLE
MOMO-15 Mainscreen 개선 사항

### ISSUE THREAD

**Issue by onmay16** [Momo-66/Momo#17]
TO-DO List
-----
- [x] 배경색 변경
- [ ] UserSlice에 MainScreen에서 쓰이는 state 및 action 추가
   * `activated`: 모모 활성화 상태
      * 메인화면 진입 시 설정된 기상시간과 현재시간을 비교해 1시간전 일 때 `momoActivated = false`로 변경될 수 있도록
   * `level`: 모모 레벨 상태
   * `streak`: 루틴 연속 달성 일수 (RoutineSlice에 들어가야 더 맞을까...?)
- [ ] 활성화 전 모모 (활성화 후도 필요하면) gif 삽입
- [ ] useEffect() 내 오늘의 루틴 데이터 가져오는 로직 필요
- [x] 내비게이션 탭 아이콘 업데이트 된 아이콘들로 수정
- [x] 내이베이션 탭 배경 색상 수정
- [ ] png 👉 svg
- [ ] 포인트 획득 animation (prioritize opacity and then yaxis movement)
- [ ] ios/안드로이드 폰트 확인
- [ ] Animation 교체 (너무 시간 잡아먹으면 걍 생략하기)

**Comment by JDhyeok** [comment]
메인화면 배경색 변경 요청드립니다 :)
