### ISSUE TITLE
[버그] 루틴 리스트 출력 오류

### ISSUE THREAD

**Issue by excel42** [Momo-66/Momo#68]
routine_collection에 최대 20개의 루틴 밖에 못 가져오는 버그 발생 

원인 : Firestore DB에서 pagination이 적용되어 최대 20개밖에 가져올 수 없음

해결방안 : 최대 조회 개수 length 20개에서 늘리는 방법 찾아보기

**Comment by JDhyeok** [comment]
리서치 결과 2가지 방안이 있음.

1. url option으로 `?pageSize=100`으로 한번에 가져올 수 있는 방안
2. response에 nextToken이 없어질 때 까지 반복해 state에 routine을 넣고 state를 사용하는 방법

(1)은 초기 적용이 빠르나 루틴 개수가 설정한 page개수보다 많게 되면 고쳐줘야 하는 번거로움이 있고, 
(2)는 초기 cost는 많이 발생하나 루팉 개수에 구애받지 않음.

일단은 (1)방안으로 PR 올릴 예정

**Comment by JDhyeok** [comment]
#64
